### ISSUE TITLE
The mod sends the mc access token to an external server

### ISSUE THREAD

**Issue by anonymous123-code** [Blutmond-Team/CloudSettings-Mod#2]
This should never be done, as it allows to login as the user. I also reported this project on mr and cf because of that:

2.0+ versions send the minecraft access token to an external server. This could be used to join servers in the name of the user. The source code linked isnt valid for those versions, use https://github.com/Blutmond-Team/CloudSettings-Mod and switch branches to the corresponding minecraft versions. Note that while the intend seems to use it for auth, this still a bad idea and there are more elegant solutions.
It is disclosed in the changelog, however.
Relevant code: https://github.com/Blutmond-Team/CloudSettings-Mod/blob/1.20/common/src/main/java/de/blutmondgilde/cloudsettings/CloudSettings.java#L45-L47 , https://github.com/Blutmond-Team/CloudSettings-Mod/blob/1.20/common/src/main/java/de/blutmondgilde/cloudsettings/api/CloudSettingsAPI.java#L102-L113

**Comment by Charismara** [comment]
Could you explain to me why this could be an issue?

The communication between users and the cloud service is ssl encrypted so the risk to lose the at to a man in the middle is basically 0, right?

And the Webapp is fully [open source](https://github.com/Blutmond-Team/CloudSettings-API). Everyone can see what data is stored and which data isn't. Just to be clear. The AT is **NOT** stored at any point.

**Comment by anonymous123-code** [comment]
One cannot ensure that the code deployed on the server is the correct one, and that forever.

**Comment by Charismara** [comment]
well you could ensure it on the [vercel push comments](https://github.com/Blutmond-Team/CloudSettings-API/commit/115cbc49add7a5fe5615f30b00e8c0da909cd9e5#commitcomment-117848847). I could change the mod remote url to the vercel domain if you feel better with that

**Comment by Charismara** [comment]
Best i can do is changing the remote url of the mod to https://cloud-settings-api-charismara.vercel.app/ which is an domain managed by the vercel bot so no one can change the target ip on that.

I have no problem making the auth process different if there is any other way to ensure the user is really the himself without the need of a login prompt.

**Comment by LostLuma** [comment]
That would still allow someone else to change the code if they gain push access to this repo, however unlikely  it is.

A better way to do authentication that other mods with similar needs implement is having the client do the same handshake as joining a multiplayer server does. An example of such a mod is Figura, however I'm unsure their backend is public for you to get inspired from at this time.

**Comment by anonymous123-code** [comment]
Even if that is the case, I cannot ensure that this is the case in the future, plus this would require that one checks the source code every deploy. (U dont make a discord bot that checks ur legitimacy by requesting ur credentials, either). It just shouldnt be sent **at all**. An alternate method might be the way AxolotlClient (https://github.com/AxolotlClient/AxolotlClient-API/blob/main/docs/tcp/v1/authentication.md) or figura (https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/blob/1.20/src/main/java/org/moon/figura/backend2/AuthHandler.java) do it

**Comment by Charismara** [comment]
Alright, this might take a while to implement but it seems reasonable to do. I'll publish an update as soon as possible.

Thank you both for suggesting this!

**Comment by anonymous123-code** [comment]
The protocol is documented at https://wiki.vg/Protocol_Encryption#Authentication

**Comment by Charismara** [comment]
alright, i got a small issue. The webapp is based on serverless functions and static rendered frontend pages which are both hosted for free on vercel. 

I can not use websockets for the auth without own resources which probably cost some money....

Any idea how to do that with serverless functions only?

**Comment by LostLuma** [comment]
The actual authentication part which obtains a Figura API token does not use websockets.
If you look at the `AuthHandler.java` file linked it does it in a three step process via normal HTTP requests:
- Ask the backend for a randomized server ID based on the user's username
- Let the Minecraft client "log in" to this server so the backend can receive the UUID etc. from Mojang w/o seeing the actual access token
- Ask the backend for the Figura token generated via the login to the specific server ID

After that this token is used with their HTTP and WS APIs, but there's no reason for you to have a websocket.

**Comment by Charismara** [comment]
> * Let the Minecraft client "log in" to this server so the backend can receive the UUID etc. from Mojang w/o seeing the actual access token

Doesn't require this part a websocket or an minecraft server to receive and send the packets?

**Comment by LostLuma** [comment]
~~Not a websocket but a socket I suppose, yeah. Sorry for the confusion.~~

**Comment by Charismara** [comment]
yeah, my bad. Those are sockets. Is there any other way to make this work without the need of an socket?

**Comment by LostLuma** [comment]
Seems my initial take was right, actually. Calling `MinecraftSessionService.joinServer` is basically a signal to the auth server that the client intends to join a server, and the server can then confirm it by calling `MinecraftSessionService.hasJoinedServer`, which is both a HTTP request (you can look at the Minecraft source for the implementation). The backend only needs to know the username of the client which you can send in the very first request that generates the server ID.

**Comment by Charismara** [comment]
So this should work with only http messages, right?

1. Client requests server id from backend
2. Server response with server id
3. Client sends server id and username with `MinecraftSessionService.joinServer` to mojang
4. Client notifies the Server that he has logged in with the server id and his username
5. Server checks the server id
6. Server checks the login state on mojang (like `MinecraftSessionService.hasJoinedServer`) does it
7. Server response with a unique session token which can be used to send request to the backend

**Comment by LostLuma** [comment]
Yes

**Comment by Charismara** [comment]
The web app should be finished now. The 2.0.0.5 updates for all version are coming soon.

Thank you guys again for suggesting this

**Comment by Charismara** [comment]
`2.0.0.5` has been published on curseforge and uploaded to modrinth (still waiting for the review of modrinth again)

All earlier 2.0.0.X version has been removed and the api will be remove soon.

**Comment by LostLuma** [comment]
Fwiw it seems like your update has a bug, the game gets stuck after logging `[21:05:10] [pool-5-thread-1/INFO]: Requested Session Token`.

**Comment by Charismara** [comment]
what version are you playing on?

I tested 1.20.1 and 1.16.5 forge and fabric. both work for me
