### ISSUE TITLE
Game hangs forever during API auth flow

### ISSUE THREAD

**Issue by LostLuma** [Blutmond-Team/CloudSettings-Mod#3]
Continued from #2 since this is not quite related anymore and I don't want to fill that person's email 🙂

I've tested version `2.0.0.5` for `1.20.1` on both Fabric and Quilt without any other mods present and both hang up at the same point. Here's a full client log: https://files.lostluma.net/ouhpHg.txt

**Comment by Charismara** [comment]
It's probably because `https://sessionserver.mojang.com/session/minecraft/hasJoined` returns an 204 instead of an 200.

Sadly i got no clue why this happends... Maybe an invalid serverid and username combo?

**Comment by Charismara** [comment]
Okay i'm now kinda sure it's the fault of this:

```ts
    // Code from Web App
    const serverHash = crypto.createHash("sha1")
        .update(body.username)
        .digest();
    const serverId = BigInt.asIntN(
        160,
        serverHash.reduce((a, x) => a << 8n | BigInt(x), 0n)
    ).toString(16);
```
which gets sent to mojang here
```java
// Code from Mod
Minecraft.getInstance().getMinecraftSessionService().joinServer(
    CloudSettings.getUser().getGameProfile(), 
    CloudSettings.getUser().getAccessToken(), 
    serverIdResponse.getServerId() //<--- value from above
);
```
and here

```ts
// Code from Web App
const mojangLoginResponse = await fetch(`https://sessionserver.mojang.com/session/minecraft/hasJoined?username=${encodeURI(body.username)}&serverId=${encodeURI(login.serverId)}`, {
        headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
        method: "GET"
    });
```

I'm probably using it wrong. Do you maybe know what I did wrong?

**Comment by Charismara** [comment]
I've changed a the way how serverIds get generated. Could u try it again please?

**Comment by LostLuma** [comment]
Works fine for me now, thanks 🙂
